modLoader="javafml" #mandatory
loaderVersion="[25,)" #botania has 28+

[[mods]]
modId="nostrummagica"
version="${file.jarVersion}"
displayName="Nostrum Magica"
#logoFile="examplemod.png" #optional
description='''
Immersive & Complex Spellcrafting
'''

[[dependencies.nostrummagica]]
	modId="forge"
	mandatory=true
	versionRange="[28.1.92,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.nostrummagica]]
	modId="curios"
	mandatory=false
	versionRange="[FORGE-1.14.4-1.0.6.1,)"
	ordering="AFTER"
	side="BOTH"

[[dependencies.nostrummagica]]
	modId="musica"
	mandatory=false
	versionRange="[1.14.4-1.0.0,)"
	ordering="AFTER"
	side="BOTH"